services:
  postgres:
    image: postgres:16
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:       